### ISSUE TITLE
Crash when trying to run rotor with phoenix

### ISSUE THREAD

**Issue by zamith** [HashNuke/rotor#1]
I'm using [sass_rotor](https://github.com/danielfarrell/sass_rotor) with the following config:

``` elixir
import Rotor.BasicRotors
import SassRotor

output_path = "priv/static/assets/application.css"
Rotor.watch :stylesheets, ["priv/assets/stylesheets/*.sass"], fn(_changed_files, all_files)->
  read_files(all_files)
  |> sass
  |> concat
  |> output_to(output_path)
end
```

On compilation I get this error:

```
** (exit) exited in: GenServer.call(Rotor.GroupServer, {:get_and_update, #Function<0.128959245/1 in Rotor.GroupServer.add/4>}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    lib/rotor/group_server.ex:23: Rotor.GroupServer.add/4
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

Is there something I'm missing here?

**Comment by HashNuke** [comment]
It looks like Rotor isn't running. Have you added :rotor to the list of applications to start, in mix.exs?

**Comment by zamith** [comment]
Yes, here is my `mix.exs`:

``` elixir
defmodule TheShelf.Mixfile do
  use Mix.Project

  def project do
    [ app: :the_shelf,
      version: "0.0.1",
      elixir: "~> 1.0.0-rc1",
      elixirc_paths: ["lib", "web", "test"],
      deps: deps ]
  end

  # Configuration for the OTP application
  def application do
    [ mod: { TheShelf, [] },
      applications: apps(Mix.env) ]
  end

  defp deps do
    [
      {:cowboy, "~> 1.0.0"},
      {:ecto, "~> 0.2.0"},
      {:hound, git: "git://github.com/HashNuke/hound.git"},
      {:phoenix, "0.4.1"},
      {:phoenix_haml, "~> 0.0.3"},
      {:postgrex, ">= 0.0.0"},
      {:rotor, git: "https://github.com/hashnuke/rotor", override: true},
      {:sass_rotor, git: "https://github.com/danielfarrell/sass_rotor"}
    ]
  end

  defp apps(:test) do
    [ :hound ] ++ apps
  end
  defp apps(_), do: apps
  defp apps do
    [ :phoenix,
      :cowboy,
      :logger,
      :postgrex,
      :ecto,
      :rotor ]
  end
end
```

I'm adding the configs in a file called `initializers.ex` in the `lib` directory. Would that be a problem?

**Comment by HashNuke** [comment]
No the place where you add the config isn't a problem at all.
Is the project available online anywhere to clone and debug?

**Comment by zamith** [comment]
Sure, you can find it [here](https://github.com/zamith/the_shelf_reborn). After installing the dependencies you should get the error just by running `mix phoenix.start`.

**Comment by HashNuke** [comment]
It looks like the rotors are being added when the application hasn't yet started.

Here's how I got it working:

_1.) I changed the `lib/initializers.ex` file to the following_

```
import Rotor.BasicRotors
import SassRotor


defmodule TheShelf.Initializers do

  def start_rotors do
    output_path = "priv/static/assets/application.css"
    Rotor.watch :stylesheets, ["priv/assets/stylesheets/*.sass"], fn(_changed_files, all_files)->
      read_files(all_files)
      |> sass
      |> concat
      |> output_to(output_path)
    end
  end

end
```

_2.) Then changed the start function in `lib/the_shelf.ex` to the following_

```
defmodule TheShelf do
  use Application

  # See http://elixir-lang.org/docs/stable/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    children = [
      worker(Repo, [])
    ]

    # we start rotors only in development
    if Mix.env == :dev do
      TheShelf.Initializers.start_rotors
    end

    opts = [strategy: :one_for_one, name: TheShelf.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

To run rotors in production, make a mix task to run them seperately one-time. There's a way for that if you register the rotors as manual, by setting the option `manual: true`. I actually have a module that registers a few rotors to act like the Rails asset pipeline. It's incomplete and doesn't work for sure. But might act as a reference - https://gist.github.com/HashNuke/98b3fb74b293cd37fb26

**Comment by HashNuke** [comment]
I'll complete it and post details later.

**Comment by zamith** [comment]
Seems to work, thanks a lot. It would be good to have more documentation on where and how to integrate the configs with an actual mix project. I was planning on adding it to phoenix as a pr, but maybe adding it here would be nice as well. What do you think?

**Comment by HashNuke** [comment]
Yes. I'm more inclined towards making the asset pipeline as a separate
package with all the defaults. So that once it's added as a dependency in
an app, things start working with no or minimal config.

**Comment by zamith** [comment]
That seems a much better workflow for sure. Is there any ongoing work on an asset pipeline? I would love to help out.

**Comment by HashNuke** [comment]
@zamith That gist I linked you to IS the asset pipeline. I started writing it as a part of another app. It is very simple tho. Wrote it for my needs, but it had sufficient defaults. Just that it is in an almost-complete state.

**Comment by zamith** [comment]
@HashNuke Oh ok. I thought you'd like to have something with a bit more features, such as:
1. Ability to register new rotors, so you'd just add an application to your project and it would work
2. Configurable load paths
3. Fingerprinting the file's name to leverage cache

Obviously there are a lot more things you can do, but these would be nice. Don't you agree?

**Comment by HashNuke** [comment]
Oh yes #2 and #3 are TODO in the gist. I never completed those functions.
That's what digested_output_to() does.
